/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainFrame;

import DAO.ChiffrementDao;
import DAO.UtilisateurDao;
import DAO.MotDePasseIncorrectException;
import Model.UtilisateurModel;
import Model.UtilisateurModel.TABLESENUM;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author l.sanchez
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private TableModelUtilisateur userTableModel;

    private Object[] tableColumns = new Object[]{"nom", "prenom", "mail", "mot de passe"};
    private Object[][] tableDatas = new Object[][]{};
    private TableModelUtilisateur tableModel = new TableModelUtilisateur();

    public MainFrame() {
        initComponents();
        UtilisateurModel utilisateurModel = new UtilisateurModel();
        try {
            UtilisateurDao utilisateurDao = new UtilisateurDao(utilisateurModel);
            var allUtilisateurs = utilisateurDao.getAll();
            for (UtilisateurModel utilisateur : allUtilisateurs) {
                String nom = UtilisateurModel.getColumnByEnum(TABLESENUM.NOM);
                String prenom = UtilisateurModel.getColumnByEnum(TABLESENUM.PRENOM);
                String mail = UtilisateurModel.getColumnByEnum(TABLESENUM.EMAIL);
                String motDePasse = UtilisateurModel.getColumnByEnum(TABLESENUM.MDP);

                this.tableModel.addUtilisateur(utilisateur);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        PanelFormLeft = new javax.swing.JPanel();
        PanelFormRight = new javax.swing.JPanel();
        tfPrenom = new javax.swing.JTextField();
        tfNom = new javax.swing.JTextField();
        tfMail = new javax.swing.JTextField();
        tfMotDePasse = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnEditUser = new javax.swing.JButton();
        btnDelUser = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        PanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Publicom [Shizu est magnifique]");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        PanelForm.setLayout(new javax.swing.BoxLayout(PanelForm, javax.swing.BoxLayout.LINE_AXIS));

        PanelFormLeft.setLayout(new javax.swing.BoxLayout(PanelFormLeft, javax.swing.BoxLayout.PAGE_AXIS));
        PanelForm.add(PanelFormLeft);

        PanelFormRight.setBackground(new java.awt.Color(51, 51, 51));
        PanelFormRight.setLayout(new javax.swing.BoxLayout(PanelFormRight, javax.swing.BoxLayout.PAGE_AXIS));

        tfPrenom.setBackground(new java.awt.Color(51, 51, 51));
        tfPrenom.setForeground(new java.awt.Color(204, 204, 204));
        tfPrenom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prenom", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        PanelFormRight.add(tfPrenom);

        tfNom.setBackground(new java.awt.Color(51, 51, 51));
        tfNom.setForeground(new java.awt.Color(204, 204, 204));
        tfNom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        tfNom.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        PanelFormRight.add(tfNom);

        tfMail.setBackground(new java.awt.Color(51, 51, 51));
        tfMail.setForeground(new java.awt.Color(204, 204, 204));
        tfMail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adresse mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        tfMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMailActionPerformed(evt);
            }
        });
        PanelFormRight.add(tfMail);

        tfMotDePasse.setBackground(new java.awt.Color(51, 51, 51));
        tfMotDePasse.setForeground(new java.awt.Color(204, 204, 204));
        tfMotDePasse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mot de passe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        tfMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMotDePasseActionPerformed(evt);
            }
        });
        PanelFormRight.add(tfMotDePasse);

        PanelForm.add(PanelFormRight);

        getContentPane().add(PanelForm);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnEditUser.setBackground(new java.awt.Color(102, 102, 102));
        btnEditUser.setForeground(new java.awt.Color(204, 204, 204));
        btnEditUser.setText("Edit");
        btnEditUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditUserMouseClicked(evt);
            }
        });
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        btnDelUser.setBackground(new java.awt.Color(102, 102, 102));
        btnDelUser.setForeground(new java.awt.Color(204, 204, 204));
        btnDelUser.setText("Suprimer");
        btnDelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelUserMouseClicked(evt);
            }
        });
        btnDelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelUserActionPerformed(evt);
            }
        });

        btnAddUser.setBackground(new java.awt.Color(102, 102, 102));
        btnAddUser.setForeground(new java.awt.Color(204, 204, 204));
        btnAddUser.setText("Ajouter");
        btnAddUser.setToolTipText("");
        btnAddUser.setOpaque(true);
        btnAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUserMouseClicked(evt);
            }
        });
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditUser, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        PanelTable.setBackground(new java.awt.Color(51, 51, 51));

        TableUser.setForeground(new java.awt.Color(51, 51, 51));
        TableUser.setModel(this.tableModel);
        TableUser.setEnabled(false);
        jScrollPane1.setViewportView(TableUser);

        javax.swing.GroupLayout PanelTableLayout = new javax.swing.GroupLayout(PanelTable);
        PanelTable.setLayout(PanelTableLayout);
        PanelTableLayout.setHorizontalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1391, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTableLayout.setVerticalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelTable);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMailActionPerformed

    private void btnEditUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditUserMouseClicked
        // TODO add your handling code here:
        System.out.println("Edit");
    }//GEN-LAST:event_btnEditUserMouseClicked

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnDelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelUserMouseClicked
        // TODO add your handling code here:
        System.out.println("Del");
    }//GEN-LAST:event_btnDelUserMouseClicked

    private void btnDelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelUserActionPerformed

    private void btnAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserMouseClicked
        // TODO add your handling code here:
        System.out.println("Add: " + this.tfMotDePasse.getText());
        this.tfMotDePasse.getText();

    }//GEN-LAST:event_btnAddUserMouseClicked

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        String nom = this.tfNom.getText();
        String prenom = this.tfPrenom.getText();
        String mail = this.tfMail.getText();
        String motDePasse = this.tfMotDePasse.getText();
        ChiffrementDao chiffrement = new ChiffrementDao();

        try {
            if (!chiffrement.checkPassword(motDePasse)) {
                throw new MotDePasseIncorrectException("Le mot de passe ne respecte pas les normes de sécurité.");
            }
            String password = chiffrement.hash(motDePasse);
            UtilisateurModel utilisateur = new UtilisateurModel(nom, prenom, mail, false, password);
            UtilisateurDao utilisateurDao;
            try {
                utilisateurDao = new UtilisateurDao(utilisateur);
                UtilisateurModel createdUtilisateur = utilisateurDao.insert(utilisateur);
                this.tableModel.addUtilisateur(utilisateur);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (MotDePasseIncorrectException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
/*
         try {
            // Vérifier si le mot de passe respecte les normes
            if (!ChiffrementDao.checkPassword(motDePasse)) {
                throw new MotDePasseIncorrectException("Le mot de passe ne respecte pas les normes de sécurité.");
            }

            // Chiffrer le mot de passe
            String motDePasseChiffre = ChiffrementDao.chiffrer(motDePasse);

            // Créer et insérer l'utilisateur
            UtilisateurModel utilisateur = new UtilisateurModel(nom, prenom, mail, false, motDePasseChiffre);
            UtilisateurDao utilisateurDao = new UtilisateurDao(utilisateur);
            utilisateurDao.insert(utilisateur);

            // Afficher un message de succès
            JOptionPane.showMessageDialog(null, "Utilisateur créé avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);

        
*/

    }//GEN-LAST:event_btnAddUserActionPerformed

    private void tfMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMotDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMotDePasseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelForm;
    private javax.swing.JPanel PanelFormLeft;
    private javax.swing.JPanel PanelFormRight;
    private javax.swing.JPanel PanelTable;
    private javax.swing.JTable TableUser;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDelUser;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfMail;
    private javax.swing.JTextField tfMotDePasse;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrenom;
    // End of variables declaration//GEN-END:variables
}
