/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import DAO.UtilisateurDao;
import Model.UtilisateurModel;
import controller.TableModelUtilisateur;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.CheckedValue;
import utils.Crypt;
import utils.exception.EmailAlreadyExistException;
import utils.validityClass.DateNaissance;
import utils.validityClass.Email;
import utils.validityClass.Nom;
import utils.validityClass.Prenom;

/**
 *
 * @author l.sanchez
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private TableModelUtilisateur tableModel;

    public MainFrame() {
        this.tableModel = new TableModelUtilisateur();
        initComponents();
        UtilisateurModel utilisateurModel = new UtilisateurModel();
        try {
            UtilisateurDao utilisateurDao = new UtilisateurDao(utilisateurModel);
            List<UtilisateurModel> allUtilisateurs = utilisateurDao.getAll();
            for (UtilisateurModel utilisateur : allUtilisateurs) {
                this.tableModel.addUtilisateur(utilisateur);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        PanelFormLeft = new javax.swing.JPanel();
        PanelFormRight = new javax.swing.JPanel();
        tfPrenom = new javax.swing.JTextField();
        tfNom = new javax.swing.JTextField();
        tfMail = new javax.swing.JTextField();
        tfMotDePasse = new javax.swing.JTextField();
        tfDateNaissance = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnDelUser = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        PanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Publicom [Shizu est magnifique]");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        PanelForm.setMaximumSize(new java.awt.Dimension(2147483647, 400));
        PanelForm.setLayout(new javax.swing.BoxLayout(PanelForm, javax.swing.BoxLayout.LINE_AXIS));

        PanelFormLeft.setLayout(new javax.swing.BoxLayout(PanelFormLeft, javax.swing.BoxLayout.PAGE_AXIS));
        PanelForm.add(PanelFormLeft);

        PanelFormRight.setBackground(new java.awt.Color(51, 51, 51));
        PanelFormRight.setLayout(new javax.swing.BoxLayout(PanelFormRight, javax.swing.BoxLayout.PAGE_AXIS));

        tfPrenom.setBackground(new java.awt.Color(51, 51, 51));
        tfPrenom.setForeground(new java.awt.Color(204, 204, 204));
        tfPrenom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prenom", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        PanelFormRight.add(tfPrenom);

        tfNom.setBackground(new java.awt.Color(51, 51, 51));
        tfNom.setForeground(new java.awt.Color(204, 204, 204));
        tfNom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        tfNom.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        PanelFormRight.add(tfNom);

        tfMail.setBackground(new java.awt.Color(51, 51, 51));
        tfMail.setForeground(new java.awt.Color(204, 204, 204));
        tfMail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adresse mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        tfMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMailActionPerformed(evt);
            }
        });
        PanelFormRight.add(tfMail);

        tfMotDePasse.setBackground(new java.awt.Color(51, 51, 51));
        tfMotDePasse.setForeground(new java.awt.Color(204, 204, 204));
        tfMotDePasse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mot de passe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        tfMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMotDePasseActionPerformed(evt);
            }
        });
        PanelFormRight.add(tfMotDePasse);

        tfDateNaissance.setBackground(new java.awt.Color(51, 51, 51));
        tfDateNaissance.setForeground(new java.awt.Color(204, 204, 204));
        tfDateNaissance.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date de naissance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        tfDateNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDateNaissanceActionPerformed(evt);
            }
        });
        PanelFormRight.add(tfDateNaissance);

        PanelForm.add(PanelFormRight);

        getContentPane().add(PanelForm);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 100));

        btnDelUser.setBackground(new java.awt.Color(102, 102, 102));
        btnDelUser.setForeground(new java.awt.Color(204, 204, 204));
        btnDelUser.setText("Suprimer");
        btnDelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelUserMouseClicked(evt);
            }
        });
        btnDelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelUserActionPerformed(evt);
            }
        });

        btnAddUser.setBackground(new java.awt.Color(102, 102, 102));
        btnAddUser.setForeground(new java.awt.Color(204, 204, 204));
        btnAddUser.setText("Ajouter");
        btnAddUser.setToolTipText("");
        btnAddUser.setOpaque(true);
        btnAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUserMouseClicked(evt);
            }
        });
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnUpdateUser.setText("Modifier mot de passe");
        btnUpdateUser.setMinimumSize(new java.awt.Dimension(27, 27));
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelUser)
                    .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        PanelTable.setBackground(new java.awt.Color(51, 51, 51));

        tableUser.setForeground(new java.awt.Color(51, 51, 51));
        tableUser.setModel(this.tableModel);
        jScrollPane1.setViewportView(tableUser);

        javax.swing.GroupLayout PanelTableLayout = new javax.swing.GroupLayout(PanelTable);
        PanelTable.setLayout(PanelTableLayout);
        PanelTableLayout.setHorizontalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTableLayout.setVerticalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelTable);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMailActionPerformed

    private void tfMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMotDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMotDePasseActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        try {

            Prenom prenom = new Prenom(this.tfPrenom.getText());
            LocalDate dateNaissanceLocalDate = LocalDate.parse(tfDateNaissance.getText());
            DateNaissance dateNaissance = new DateNaissance(dateNaissanceLocalDate.toString());
            Nom nom = new Nom(this.tfNom.getText());
            Email mail = new Email(this.tfMail.getText());
            String motDePasse = this.tfMotDePasse.getText();
            Crypt chiffrement = new Crypt();

            var checkedPassword = chiffrement.checkPassword(motDePasse);
            if (checkedPassword.isValid()) {
                String password = chiffrement.hash(motDePasse);
                UtilisateurModel utilisateur = new UtilisateurModel(nom, prenom, mail, false, password, dateNaissance);
                UtilisateurDao utilisateurDao;
                try {
                    utilisateurDao = new UtilisateurDao(utilisateur);
                    UtilisateurModel createdUtilisateur = utilisateurDao.insert(utilisateur);
                    this.tableModel.addUtilisateur(utilisateur);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Erreur Serveur", "Erreur", JOptionPane.ERROR_MESSAGE);
                } catch(EmailAlreadyExistException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Email existe deja", "Erreur", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erreur Inconnu", "Erreur", JOptionPane.ERROR_MESSAGE);
                    System.err.println("Mainframe.btnAddUserActionPerformed() : " + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, checkedPassword.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }catch(DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Date invalide veuillez respecter le format (AAAA-MM-JJ)", "Erreur", JOptionPane.ERROR_MESSAGE);
        } 
        catch (Exception ex) {
            System.out.println(ex);
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Erreur inconnu", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserMouseClicked

    }//GEN-LAST:event_btnAddUserMouseClicked

    private void btnDelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelUserActionPerformed
        int[] selectedRows = this.tableUser.getSelectedRows();

        /*
         * Boucle inverse pour supprimer les lignes du tableau par le bas Sinon
         * des exceptions apparaissent. Pourquoi : tableau de taille 4. je
         * recupere la valeur 0 pour la supprimer. je la supprime (tableau
         * taille 3) je recupere la valeur 1 pour la supprimer. je la supprime
         * (tableau taille 2) je recupere la valeur 2 pour la supprimer. je la
         * supprime impossible puisque la derniere valeur est en position 1
         */
        for (int i = selectedRows.length - 1; i >= 0; i--) {
            System.out.println("i : " + i);
            int selectedRow = selectedRows[i];
            UtilisateurModel selectedUser = this.tableModel.getRow(selectedRow);
            try {
                UtilisateurDao utilisateurDao = new UtilisateurDao(selectedUser);
                utilisateurDao.delete(selectedUser);
                this.tableModel.removeUtilisateur(selectedUser);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDelUserActionPerformed

    private void btnDelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelUserMouseClicked
        // TODO add your handling code here:
        System.out.println("Del");
    }//GEN-LAST:event_btnDelUserMouseClicked

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        int[] selectedRows = this.tableUser.getSelectedRows();
        if (selectedRows.length == 1) {
            int selectedRow = selectedRows[0];
            UtilisateurModel utilisateur = this.tableModel.getRow(selectedRow);
            String newPass = JOptionPane.showInputDialog(this, "mon message", "**********");
            Crypt chiffrement = new Crypt();
            CheckedValue checkedPassword = chiffrement.checkPassword(newPass);
            if (checkedPassword.isValid()) {
                String hashedPassword = chiffrement.hash(newPass);
                utilisateur.set(UtilisateurModel.TABLESENUM.MDP, hashedPassword);
                UtilisateurDao utilisateurDao;
                try {
                    utilisateurDao = new UtilisateurDao(utilisateur);
                    utilisateurDao.update(utilisateur);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erreur Serveur", "Erreur", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erreur Inconnu", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, checkedPassword.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "une et une seule ligne doit etre selectionne", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void tfDateNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDateNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDateNaissanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelForm;
    private javax.swing.JPanel PanelFormLeft;
    private javax.swing.JPanel PanelFormRight;
    private javax.swing.JPanel PanelTable;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDelUser;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUser;
    private javax.swing.JTextField tfDateNaissance;
    private javax.swing.JTextField tfMail;
    private javax.swing.JTextField tfMotDePasse;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrenom;
    // End of variables declaration//GEN-END:variables
}
